kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mssql
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi